issues:
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  disable-all: true
  enable:
    - bodyclose
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - goconst
    - gofumpt
    - gomnd
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - lll
    - misspell
    - musttag
    - nosprintfhostport
    - prealloc
    - predeclared
    - reassign
    - revive
    - staticcheck
    - tagliatelle
    - thelper
    - typecheck
    - unconvert
    - unused
    - usestdlibvars
