issues:
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  disable-all: true
  enable:
    - bodyclose
    - errname
    - errorlint
    - errcheck
    - exhaustive
    - gofumpt
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - prealloc
    - staticcheck
    - thelper
    - typecheck
    - unconvert
    - unused
    - usestdlibvars
